////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicOCurvesSchema_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at OCurvesSchema.kl:9:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_construct")
}

// Defined at OCurvesSchema.kl:10:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_free")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::OCurvesSchema)
  
  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_free")
}

// Defined at OCurvesSchema.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOCurvesSchema_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_valid")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCurvesSchema_valid", false)
}

// Defined at OCurvesSchema.kl:14:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_getTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicTimeSampling >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_getTimeSampling")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_getTimeSampling. unable to convert: this_");
    return;
  }
  Abc::TimeSamplingPtr abc_result = abcThis_->getTimeSampling();
  conv_to_AbcBase<KL::AlembicTimeSampling, Abc::TimeSamplingPtr>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_getTimeSampling")
}

// Defined at OCurvesSchema.kl:15:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicOCurvesSchema_getNumSamples(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_getNumSamples")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_getNumSamples. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getNumSamples();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCurvesSchema_getNumSamples", 0)
}

// Defined at OCurvesSchema.kl:16:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_set(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSample >::INParam sample
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_set")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_set. unable to convert: this_");
    return;
  }
  AbcG::OCurvesSchema::Sample * abcSample = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSample, AbcG::OCurvesSchema::Sample>(sample, abcSample)){
    setError("Error in AlembicOCurvesSchema_set. unable to convert: sample");
    return;
  }
  abcThis_->set(*abcSample);

  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_set")
}

// Defined at OCurvesSchema.kl:17:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_setFromPrevious(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_setFromPrevious")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_setFromPrevious. unable to convert: this_");
    return;
  }
  abcThis_->setFromPrevious();

  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_setFromPrevious")
}

// Defined at OCurvesSchema.kl:18:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_setTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_setTimeSampling")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_setTimeSampling. unable to convert: this_");
    return;
  }
  unsigned int abcIndex = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(index, abcIndex)){
    setError("Error in AlembicOCurvesSchema_setTimeSampling. unable to convert: index");
    return;
  }
  abcThis_->setTimeSampling(abcIndex);

  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_setTimeSampling")
}

// Defined at OCurvesSchema.kl:19:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_getArbGeomParams(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_getArbGeomParams")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_getArbGeomParams. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getArbGeomParams());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_getArbGeomParams")
}

// Defined at OCurvesSchema.kl:20:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_getUserProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_getUserProperties")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_getUserProperties. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getUserProperties());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_getUserProperties")
}

// Defined at OCurvesSchema.kl:21:1
FABRIC_EXT_EXPORT void AlembicOCurvesSchema_getChildBoundsProperty(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOScalarProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCurvesSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCurvesSchema_getChildBoundsProperty")

  AbcG::OCurvesSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCurvesSchema, AbcG::OCurvesSchema>(this_, abcThis_)){
    setError("Error in AlembicOCurvesSchema_getChildBoundsProperty. unable to convert: this_");
    return;
  }
  Abc::OScalarProperty* abc_result = new Abc::OScalarProperty(abcThis_->getChildBoundsProperty());
  conv_to_AbcBasePtr<KL::AlembicOScalarProperty, Abc::OScalarProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOCurvesSchema_getChildBoundsProperty")
}
