////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicICurves_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at ICurves.kl:9:1
FABRIC_EXT_EXPORT void AlembicICurves_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurves >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICurves_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicICurves_construct")
}

// Defined at ICurves.kl:10:1
FABRIC_EXT_EXPORT void AlembicICurves_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurves >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICurves_free")

  AbcG::ICurves* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICurves, AbcG::ICurves>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::ICurves)
  
  ALEMBIC_CATCH_STATEMENT("AlembicICurves_free")
}

// Defined at ICurves.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicICurves_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurves >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICurves_valid")

  AbcG::ICurves* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICurves, AbcG::ICurves>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicICurves_valid", false)
}

// Defined at ICurves.kl:14:1
FABRIC_EXT_EXPORT void AlembicICurves_constructFromIObject(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurves >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIObject >::INParam obj
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICurves_constructFromIObject")

  Abc::IObject* abcObj = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIObject, Abc::IObject>(obj, abcObj)){
    setError("Error in AlembicICurves_constructFromIObject. unable to convert: obj");
    return;
  }

  AbcG::ICurves * abcThis_ = new AbcG::ICurves(*abcObj, Abc::kWrapExisting);
  this_->handle = new PtrHandle<AbcG::ICurves>(abcThis_, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicICurves_constructFromIObject")
}

// Defined at ICurves.kl:19:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicICurves_matches(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurves >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::INParam metaData
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICurves_matches")

  Abc::MetaData * abcMetaData = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicMetaData, Abc::MetaData>(metaData, abcMetaData)){
    setError("Error in AlembicICurves_matches. unable to convert: metaData");
    return false;
  }
  return AbcG::ICurves::matches(*abcMetaData);
  
  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicICurves_matches", false)
}

// Defined at ICurves.kl:20:1
FABRIC_EXT_EXPORT void AlembicICurves_getSchema(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurvesSchema >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurves >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICurves_getSchema")

  AbcG::ICurves* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICurves, AbcG::ICurves>(this_, abcThis_)){
    setError("Error in AlembicICurves_getSchema. unable to convert: this_");
    return;
  }
  AbcG::ICurvesSchema* abc_result = new AbcG::ICurvesSchema(abcThis_->getSchema());
  conv_to_AbcBasePtr<KL::AlembicICurvesSchema, AbcG::ICurvesSchema>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicICurves_getSchema")
}

// Defined at ICurves.kl:21:1
FABRIC_EXT_EXPORT void AlembicICurves_getProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICurves >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICurves_getProperties")

  AbcG::ICurves* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICurves, AbcG::ICurves>(this_, abcThis_)){
    setError("Error in AlembicICurves_getProperties. unable to convert: this_");
    return;
  }
  Abc::ICompoundProperty* abc_result = new Abc::ICompoundProperty(abcThis_->getProperties());
  conv_to_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicICurves_getProperties")
}
