////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicONuPatchSchema_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at ONuPatchSchema.kl:9:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_construct")
}

// Defined at ONuPatchSchema.kl:10:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_free")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::ONuPatchSchema)
  
  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_free")
}

// Defined at ONuPatchSchema.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicONuPatchSchema_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_valid")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicONuPatchSchema_valid", false)
}

// Defined at ONuPatchSchema.kl:14:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_getTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicTimeSampling >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_getTimeSampling")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_getTimeSampling. unable to convert: this_");
    return;
  }
  Abc::TimeSamplingPtr abc_result = abcThis_->getTimeSampling();
  conv_to_AbcBase<KL::AlembicTimeSampling, Abc::TimeSamplingPtr>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_getTimeSampling")
}

// Defined at ONuPatchSchema.kl:15:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicONuPatchSchema_getNumSamples(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_getNumSamples")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_getNumSamples. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getNumSamples();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicONuPatchSchema_getNumSamples", 0)
}

// Defined at ONuPatchSchema.kl:16:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_set(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSample >::INParam sample
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_set")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_set. unable to convert: this_");
    return;
  }
  AbcG::ONuPatchSchema::Sample * abcSample = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSample, AbcG::ONuPatchSchema::Sample>(sample, abcSample)){
    setError("Error in AlembicONuPatchSchema_set. unable to convert: sample");
    return;
  }
  abcThis_->set(*abcSample);

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_set")
}

// Defined at ONuPatchSchema.kl:17:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_setFromPrevious(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_setFromPrevious")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_setFromPrevious. unable to convert: this_");
    return;
  }
  abcThis_->setFromPrevious();

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_setFromPrevious")
}

// Defined at ONuPatchSchema.kl:18:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_setTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_setTimeSampling")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_setTimeSampling. unable to convert: this_");
    return;
  }
  unsigned int abcIndex = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(index, abcIndex)){
    setError("Error in AlembicONuPatchSchema_setTimeSampling. unable to convert: index");
    return;
  }
  abcThis_->setTimeSampling(abcIndex);

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_setTimeSampling")
}

// Defined at ONuPatchSchema.kl:19:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_getArbGeomParams(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_getArbGeomParams")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_getArbGeomParams. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getArbGeomParams());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_getArbGeomParams")
}

// Defined at ONuPatchSchema.kl:20:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_getUserProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_getUserProperties")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_getUserProperties. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getUserProperties());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_getUserProperties")
}

// Defined at ONuPatchSchema.kl:21:1
FABRIC_EXT_EXPORT void AlembicONuPatchSchema_getChildBoundsProperty(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOScalarProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatchSchema_getChildBoundsProperty")

  AbcG::ONuPatchSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(this_, abcThis_)){
    setError("Error in AlembicONuPatchSchema_getChildBoundsProperty. unable to convert: this_");
    return;
  }
  Abc::OScalarProperty* abc_result = new Abc::OScalarProperty(abcThis_->getChildBoundsProperty());
  conv_to_AbcBasePtr<KL::AlembicOScalarProperty, Abc::OScalarProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatchSchema_getChildBoundsProperty")
}
