////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicILight_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at ILight.kl:9:1
FABRIC_EXT_EXPORT void AlembicILight_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILight >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicILight_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicILight_construct")
}

// Defined at ILight.kl:10:1
FABRIC_EXT_EXPORT void AlembicILight_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILight >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicILight_free")

  AbcG::ILight* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicILight, AbcG::ILight>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::ILight)
  
  ALEMBIC_CATCH_STATEMENT("AlembicILight_free")
}

// Defined at ILight.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicILight_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILight >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicILight_valid")

  AbcG::ILight* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicILight, AbcG::ILight>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicILight_valid", false)
}

// Defined at ILight.kl:14:1
FABRIC_EXT_EXPORT void AlembicILight_constructFromIObject(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILight >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIObject >::INParam obj
)
{
  ALEMBIC_TRY_STATEMENT("AlembicILight_constructFromIObject")

  Abc::IObject* abcObj = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIObject, Abc::IObject>(obj, abcObj)){
    setError("Error in AlembicILight_constructFromIObject. unable to convert: obj");
    return;
  }

  AbcG::ILight * abcThis_ = new AbcG::ILight(*abcObj, Abc::kWrapExisting);
  this_->handle = new PtrHandle<AbcG::ILight>(abcThis_, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicILight_constructFromIObject")
}

// Defined at ILight.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicILight_matches(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILight >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::INParam metaData
)
{
  ALEMBIC_TRY_STATEMENT("AlembicILight_matches")

  Abc::MetaData * abcMetaData = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicMetaData, Abc::MetaData>(metaData, abcMetaData)){
    setError("Error in AlembicILight_matches. unable to convert: metaData");
    return false;
  }
  return AbcG::ILight::matches(*abcMetaData);
  
  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicILight_matches", false)
}

// Defined at ILight.kl:19:1
FABRIC_EXT_EXPORT void AlembicILight_getSchema(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILightSchema >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILight >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicILight_getSchema")

  AbcG::ILight* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicILight, AbcG::ILight>(this_, abcThis_)){
    setError("Error in AlembicILight_getSchema. unable to convert: this_");
    return;
  }
  AbcG::ILightSchema* abc_result = new AbcG::ILightSchema(abcThis_->getSchema());
  conv_to_AbcBasePtr<KL::AlembicILightSchema, AbcG::ILightSchema>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicILight_getSchema")
}

// Defined at ILight.kl:20:1
FABRIC_EXT_EXPORT void AlembicILight_getProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicILight >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicILight_getProperties")

  AbcG::ILight* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicILight, AbcG::ILight>(this_, abcThis_)){
    setError("Error in AlembicILight_getProperties. unable to convert: this_");
    return;
  }
  Abc::ICompoundProperty* abc_result = new Abc::ICompoundProperty(abcThis_->getProperties());
  conv_to_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicILight_getProperties")
}
