////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicOPoints_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at OPoints.kl:9:1
FABRIC_EXT_EXPORT void AlembicOPoints_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPoints >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPoints_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicOPoints_construct")
}

// Defined at OPoints.kl:10:1
FABRIC_EXT_EXPORT void AlembicOPoints_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPoints >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPoints_free")

  AbcG::OPoints* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPoints, AbcG::OPoints>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::OPoints)
  
  ALEMBIC_CATCH_STATEMENT("AlembicOPoints_free")
}

// Defined at OPoints.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOPoints_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPoints >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPoints_valid")

  AbcG::OPoints* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPoints, AbcG::OPoints>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOPoints_valid", false)
}

// Defined at OPoints.kl:14:1
FABRIC_EXT_EXPORT void AlembicOPoints_construct3Args(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPoints >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOObject >::INParam parent,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam timeSampling
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPoints_construct3Args")

  Abc::OObject* abcParent = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOObject, Abc::OObject>(parent, abcParent)){
    setError("Error in AlembicOPoints_construct3Args. unable to convert: parent");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicOPoints_construct3Args. unable to convert: name");
    return;
  }
  unsigned int abcTimeSampling = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(timeSampling, abcTimeSampling)){
    setError("Error in AlembicOPoints_construct3Args. unable to convert: timeSampling");
    return;
  }

  AbcG::OPoints * abcThis_ = new AbcG::OPoints(*abcParent, abcName, abcTimeSampling);
  this_->handle = new PtrHandle<AbcG::OPoints>(abcThis_, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicOPoints_construct3Args")
}

// Defined at OPoints.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOPoints_matches(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPoints >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::INParam metaData
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPoints_matches")

  AbcG::OPoints* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPoints, AbcG::OPoints>(this_, abcThis_)){
    setError("Error in AlembicOPoints_matches. unable to convert: this_");
    return false;
  }
  Abc::MetaData * abcMetaData = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicMetaData, Abc::MetaData>(metaData, abcMetaData)){
    setError("Error in AlembicOPoints_matches. unable to convert: metaData");
    return false;
  }
  return AbcG::OPoints::matches(*abcMetaData);
  
  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOPoints_matches", false)
}

// Defined at OPoints.kl:19:1
FABRIC_EXT_EXPORT void AlembicOPoints_getSchema(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPointsSchema >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPoints >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPoints_getSchema")

  AbcG::OPoints* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPoints, AbcG::OPoints>(this_, abcThis_)){
    setError("Error in AlembicOPoints_getSchema. unable to convert: this_");
    return;
  }
  AbcG::OPointsSchema* abc_result = new AbcG::OPointsSchema(abcThis_->getSchema());
  conv_to_AbcBasePtr<KL::AlembicOPointsSchema, AbcG::OPointsSchema>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOPoints_getSchema")
}
