////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicICamera_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at ICamera.kl:9:1
FABRIC_EXT_EXPORT void AlembicICamera_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICamera >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICamera_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicICamera_construct")
}

// Defined at ICamera.kl:10:1
FABRIC_EXT_EXPORT void AlembicICamera_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICamera >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICamera_free")

  AbcG::ICamera* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICamera, AbcG::ICamera>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::ICamera)
  
  ALEMBIC_CATCH_STATEMENT("AlembicICamera_free")
}

// Defined at ICamera.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicICamera_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICamera >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICamera_valid")

  AbcG::ICamera* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICamera, AbcG::ICamera>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicICamera_valid", false)
}

// Defined at ICamera.kl:14:1
FABRIC_EXT_EXPORT void AlembicICamera_constructFromIObject(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICamera >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIObject >::INParam obj
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICamera_constructFromIObject")

  Abc::IObject* abcObj = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIObject, Abc::IObject>(obj, abcObj)){
    setError("Error in AlembicICamera_constructFromIObject. unable to convert: obj");
    return;
  }

  AbcG::ICamera * abcThis_ = new AbcG::ICamera(*abcObj, Abc::kWrapExisting);
  this_->handle = new PtrHandle<AbcG::ICamera>(abcThis_, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicICamera_constructFromIObject")
}

// Defined at ICamera.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicICamera_matches(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICamera >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::INParam metaData
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICamera_matches")

  Abc::MetaData * abcMetaData = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicMetaData, Abc::MetaData>(metaData, abcMetaData)){
    setError("Error in AlembicICamera_matches. unable to convert: metaData");
    return false;
  }
  return AbcG::ICamera::matches(*abcMetaData);
  
  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicICamera_matches", false)
}

// Defined at ICamera.kl:19:1
FABRIC_EXT_EXPORT void AlembicICamera_getSchema(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICamera >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICamera_getSchema")

  AbcG::ICamera* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICamera, AbcG::ICamera>(this_, abcThis_)){
    setError("Error in AlembicICamera_getSchema. unable to convert: this_");
    return;
  }
  AbcG::ICameraSchema* abc_result = new AbcG::ICameraSchema(abcThis_->getSchema());
  conv_to_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicICamera_getSchema")
}

// Defined at ICamera.kl:20:1
FABRIC_EXT_EXPORT void AlembicICamera_getProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICamera >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICamera_getProperties")

  AbcG::ICamera* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICamera, AbcG::ICamera>(this_, abcThis_)){
    setError("Error in AlembicICamera_getProperties. unable to convert: this_");
    return;
  }
  Abc::ICompoundProperty* abc_result = new Abc::ICompoundProperty(abcThis_->getProperties());
  conv_to_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicICamera_getProperties")
}
