////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicICameraSchema_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at ICameraSchema.kl:9:1
FABRIC_EXT_EXPORT void AlembicICameraSchema_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicICameraSchema_construct")
}

// Defined at ICameraSchema.kl:10:1
FABRIC_EXT_EXPORT void AlembicICameraSchema_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_free")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::ICameraSchema)
  
  ALEMBIC_CATCH_STATEMENT("AlembicICameraSchema_free")
}

// Defined at ICameraSchema.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicICameraSchema_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_valid")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicICameraSchema_valid", false)
}

// Defined at ICameraSchema.kl:14:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicICameraSchema_isConstant(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_isConstant")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    setError("Error in AlembicICameraSchema_isConstant. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isConstant();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicICameraSchema_isConstant", false)
}

// Defined at ICameraSchema.kl:15:1
FABRIC_EXT_EXPORT void AlembicICameraSchema_get(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicCameraSample >::IOParam sample,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam ss
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_get")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    setError("Error in AlembicICameraSchema_get. unable to convert: this_");
    return;
  }
  AbcG::CameraSample * abcSample = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicCameraSample, AbcG::CameraSample>(sample, abcSample)){
    setError("Error in AlembicICameraSchema_get. unable to convert: sample");
    return;
  }
  Abc::ISampleSelector* abcSs = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(ss, abcSs)){
    setError("Error in AlembicICameraSchema_get. unable to convert: ss");
    return;
  }
  abcThis_->get(*abcSample, *abcSs);
  conv_to_AbcBasePtr<KL::AlembicCameraSample, AbcG::CameraSample>(abcSample, sample);

  ALEMBIC_CATCH_STATEMENT("AlembicICameraSchema_get")
}

// Defined at ICameraSchema.kl:17:1
FABRIC_EXT_EXPORT void AlembicICameraSchema_getTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicTimeSampling >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_getTimeSampling")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    setError("Error in AlembicICameraSchema_getTimeSampling. unable to convert: this_");
    return;
  }
  Abc::TimeSamplingPtr abc_result = abcThis_->getTimeSampling();
  conv_to_AbcBase<KL::AlembicTimeSampling, Abc::TimeSamplingPtr>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicICameraSchema_getTimeSampling")
}

// Defined at ICameraSchema.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicICameraSchema_getNumSamples(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_getNumSamples")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    setError("Error in AlembicICameraSchema_getNumSamples. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getNumSamples();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicICameraSchema_getNumSamples", 0)
}

// Defined at ICameraSchema.kl:19:1
FABRIC_EXT_EXPORT void AlembicICameraSchema_getArbGeomParams(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_getArbGeomParams")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    setError("Error in AlembicICameraSchema_getArbGeomParams. unable to convert: this_");
    return;
  }
  if(!abcThis_->getArbGeomParams().valid())
    return;
  Abc::ICompoundProperty* abc_result = new Abc::ICompoundProperty(abcThis_->getArbGeomParams());
  conv_to_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicICameraSchema_getArbGeomParams")
}

// Defined at ICameraSchema.kl:20:1
FABRIC_EXT_EXPORT void AlembicICameraSchema_getUserProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_getUserProperties")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    setError("Error in AlembicICameraSchema_getUserProperties. unable to convert: this_");
    return;
  }
  if(!abcThis_->getUserProperties().valid())
    return;
  Abc::ICompoundProperty* abc_result = new Abc::ICompoundProperty(abcThis_->getUserProperties());
  conv_to_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicICameraSchema_getUserProperties")
}

// Defined at ICameraSchema.kl:21:1
FABRIC_EXT_EXPORT void AlembicICameraSchema_getChildBoundsProperty(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIScalarProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICameraSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicICameraSchema_getChildBoundsProperty")

  AbcG::ICameraSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICameraSchema, AbcG::ICameraSchema>(this_, abcThis_)){
    setError("Error in AlembicICameraSchema_getChildBoundsProperty. unable to convert: this_");
    return;
  }
  if(!abcThis_->getChildBoundsProperty().valid())
    return;
  Abc::IScalarProperty* abc_result = new Abc::IScalarProperty(abcThis_->getChildBoundsProperty());
  conv_to_AbcBasePtr<KL::AlembicIScalarProperty, Abc::IScalarProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicICameraSchema_getChildBoundsProperty")
}
