////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicOSubDSchema_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at OSubDSchema.kl:9:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_construct")
}

// Defined at OSubDSchema.kl:10:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_free")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::OSubDSchema)
  
  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_free")
}

// Defined at OSubDSchema.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOSubDSchema_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_valid")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOSubDSchema_valid", false)
}

// Defined at OSubDSchema.kl:14:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_getTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicTimeSampling >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_getTimeSampling")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_getTimeSampling. unable to convert: this_");
    return;
  }
  Abc::TimeSamplingPtr abc_result = abcThis_->getTimeSampling();
  conv_to_AbcBase<KL::AlembicTimeSampling, Abc::TimeSamplingPtr>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_getTimeSampling")
}

// Defined at OSubDSchema.kl:15:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicOSubDSchema_getNumSamples(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_getNumSamples")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_getNumSamples. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getNumSamples();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOSubDSchema_getNumSamples", 0)
}

// Defined at OSubDSchema.kl:16:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_set(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSample >::INParam sample
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_set")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_set. unable to convert: this_");
    return;
  }
  AbcG::OSubDSchema::Sample * abcSample = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSample, AbcG::OSubDSchema::Sample>(sample, abcSample)){
    setError("Error in AlembicOSubDSchema_set. unable to convert: sample");
    return;
  }
  abcThis_->set(*abcSample);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_set")
}

// Defined at OSubDSchema.kl:17:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_setFromPrevious(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_setFromPrevious")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_setFromPrevious. unable to convert: this_");
    return;
  }
  abcThis_->setFromPrevious();

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_setFromPrevious")
}

// Defined at OSubDSchema.kl:18:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_setTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_setTimeSampling")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_setTimeSampling. unable to convert: this_");
    return;
  }
  unsigned int abcIndex = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(index, abcIndex)){
    setError("Error in AlembicOSubDSchema_setTimeSampling. unable to convert: index");
    return;
  }
  abcThis_->setTimeSampling(abcIndex);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_setTimeSampling")
}

// Defined at OSubDSchema.kl:19:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_getArbGeomParams(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_getArbGeomParams")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_getArbGeomParams. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getArbGeomParams());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_getArbGeomParams")
}

// Defined at OSubDSchema.kl:20:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_getUserProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_getUserProperties")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_getUserProperties. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getUserProperties());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_getUserProperties")
}

// Defined at OSubDSchema.kl:21:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_getChildBoundsProperty(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOScalarProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_getChildBoundsProperty")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_getChildBoundsProperty. unable to convert: this_");
    return;
  }
  Abc::OScalarProperty* abc_result = new Abc::OScalarProperty(abcThis_->getChildBoundsProperty());
  conv_to_AbcBasePtr<KL::AlembicOScalarProperty, Abc::OScalarProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_getChildBoundsProperty")
}

// Defined at OSubDSchema.kl:22:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_createFaceSet(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOFaceSet >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_createFaceSet")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_createFaceSet. unable to convert: this_");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicOSubDSchema_createFaceSet. unable to convert: name");
    return;
  }
  AbcG::OFaceSet* abc_result = new AbcG::OFaceSet(abcThis_->createFaceSet(abcName));
  conv_to_AbcBasePtr<KL::AlembicOFaceSet, AbcG::OFaceSet>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_createFaceSet")
}

// Defined at OSubDSchema.kl:23:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_getFaceSetNames(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_getFaceSetNames")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_getFaceSetNames. unable to convert: this_");
    return;
  }

  std::vector<std::string> abc_result;
  abcThis_->getFaceSetNames(abc_result);
  _result.resize(abc_result.size());
  for(size_t i=0;i<abc_result.size();i++)
    _result[i] = abc_result[i].c_str();
    
  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_getFaceSetNames")
}

// Defined at OSubDSchema.kl:24:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_getFaceSet(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOFaceSet >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_getFaceSet")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_getFaceSet. unable to convert: this_");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicOSubDSchema_getFaceSet. unable to convert: name");
    return;
  }
  AbcG::OFaceSet* abc_result = new AbcG::OFaceSet(abcThis_->getFaceSet(abcName));
  conv_to_AbcBasePtr<KL::AlembicOFaceSet, AbcG::OFaceSet>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_getFaceSet")
}

// Defined at OSubDSchema.kl:25:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOSubDSchema_hasFaceSet(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_hasFaceSet")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_hasFaceSet. unable to convert: this_");
    return false;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicOSubDSchema_hasFaceSet. unable to convert: name");
    return false;
  }
  bool abc_result = abcThis_->hasFaceSet(abcName);
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOSubDSchema_hasFaceSet", false)
}

// Defined at OSubDSchema.kl:26:1
FABRIC_EXT_EXPORT void AlembicOSubDSchema_setUVSourceName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOSubDSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOSubDSchema_setUVSourceName")

  AbcG::OSubDSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOSubDSchema, AbcG::OSubDSchema>(this_, abcThis_)){
    setError("Error in AlembicOSubDSchema_setUVSourceName. unable to convert: this_");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicOSubDSchema_setUVSourceName. unable to convert: name");
    return;
  }
  abcThis_->setUVSourceName(abcName);

  ALEMBIC_CATCH_STATEMENT("AlembicOSubDSchema_setUVSourceName")
}
