////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicIArrayProperty_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at IArrayProperty.kl:9:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_construct")
}

// Defined at IArrayProperty.kl:10:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_free")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(Abc::IArrayProperty)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_free")
}

// Defined at IArrayProperty.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicIArrayProperty_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_valid")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_valid", false)
}

// Defined at IArrayProperty.kl:14:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getHeader(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicPropertyHeader >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getHeader")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getHeader. unable to convert: this_");
    return;
  }
  AlembicPropertyGetHeader()
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getHeader")
}

// Defined at IArrayProperty.kl:15:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getName")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getName. unable to convert: this_");
    return;
  }
  std::string abc_result = abcThis_->getName();
  conv_to_String(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getName")
}

// Defined at IArrayProperty.kl:16:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicIArrayProperty_getPropertyType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getPropertyType")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getPropertyType. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getPropertyType();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_getPropertyType", 0)
}

// Defined at IArrayProperty.kl:17:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicIArrayProperty_isScalar(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_isScalar")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_isScalar. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isScalar();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_isScalar", false)
}

// Defined at IArrayProperty.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicIArrayProperty_isArray(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_isArray")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_isArray. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isArray();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_isArray", false)
}

// Defined at IArrayProperty.kl:19:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicIArrayProperty_isCompound(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_isCompound")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_isCompound. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isCompound();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_isCompound", false)
}

// Defined at IArrayProperty.kl:20:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicIArrayProperty_isSimple(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_isSimple")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_isSimple. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isSimple();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_isSimple", false)
}

// Defined at IArrayProperty.kl:21:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getMetaData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getMetaData")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getMetaData. unable to convert: this_");
    return;
  }
  AlembicGetMetaData()
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getMetaData")
}

// Defined at IArrayProperty.kl:22:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getDataType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicDataType >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getDataType")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getDataType. unable to convert: this_");
    return;
  }
  Abc::DataType abc_result = abcThis_->getDataType();
  conv_to_AbcBase<KL::AlembicDataType, Abc::DataType>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getDataType")
}

// Defined at IArrayProperty.kl:23:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicTimeSampling >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getTimeSampling")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getTimeSampling. unable to convert: this_");
    return;
  }
  Abc::TimeSamplingPtr abc_result = abcThis_->getTimeSampling();
  conv_to_AbcBase<KL::AlembicTimeSampling, Abc::TimeSamplingPtr>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getTimeSampling")
}

// Defined at IArrayProperty.kl:24:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getObject(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIObject >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getObject")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getObject. unable to convert: this_");
    return;
  }
  Abc::IObject* abc_result = new Abc::IObject(abcThis_->getObject());
  conv_to_AbcBasePtr<KL::AlembicIObject, Abc::IObject>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getObject")
}

// Defined at IArrayProperty.kl:26:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_construct2Args(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::INParam parent,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_construct2Args")

  Abc::ICompoundProperty* abcParent = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(parent, abcParent)){
    setError("Error in AlembicIArrayProperty_construct2Args. unable to convert: parent");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicIArrayProperty_construct2Args. unable to convert: name");
    return;
  }

  Abc::IArrayProperty * abcProp = new Abc::IArrayProperty(*abcParent, abcName);
  this_->handle = new PtrHandle<Abc::IArrayProperty>(abcProp, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_construct2Args")
}

// Defined at IArrayProperty.kl:28:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicIArrayProperty_getNumSamples(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getNumSamples")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getNumSamples. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getNumSamples();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_getNumSamples", 0)
}

// Defined at IArrayProperty.kl:29:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicIArrayProperty_isConstant(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_isConstant")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_isConstant. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isConstant();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_isConstant", false)
}

// Defined at IArrayProperty.kl:30:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicIArrayProperty_isScalarLike(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_isScalarLike")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_isScalarLike. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isScalarLike();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicIArrayProperty_isScalarLike", false)
}

// Defined at IArrayProperty.kl:31:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getParent(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getParent")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getParent. unable to convert: this_");
    return;
  }
  Abc::ICompoundProperty* abc_result = new Abc::ICompoundProperty(abcThis_->getParent());
  conv_to_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getParent")
}

// Defined at IArrayProperty.kl:33:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsBoolean(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Boolean > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsBoolean")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsBoolean. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(Boolean, kBooleanPOD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsBoolean")
}

// Defined at IArrayProperty.kl:34:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsBooleanWithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Boolean > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsBooleanWithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsBooleanWithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsBooleanWithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(Boolean, kBooleanPOD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsBooleanWithISS")
}

// Defined at IArrayProperty.kl:35:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt8(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt8 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt8")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt8. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(UInt8, kUint8POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt8")
}

// Defined at IArrayProperty.kl:36:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt8WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt8 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt8WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt8WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsUInt8WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(UInt8, kUint8POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt8WithISS")
}

// Defined at IArrayProperty.kl:37:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt8(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt8 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt8")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt8. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(SInt8, kInt8POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt8")
}

// Defined at IArrayProperty.kl:38:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt8WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt8 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt8WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt8WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsSInt8WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(SInt8, kInt8POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt8WithISS")
}

// Defined at IArrayProperty.kl:39:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt16(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt16 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt16")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt16. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(UInt16, kUint16POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt16")
}

// Defined at IArrayProperty.kl:40:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt16WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt16 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt16WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt16WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsUInt16WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(UInt16, kUint16POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt16WithISS")
}

// Defined at IArrayProperty.kl:41:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt16(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt16 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt16")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt16. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(SInt16, kInt16POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt16")
}

// Defined at IArrayProperty.kl:42:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt16WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt16 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt16WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt16WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsSInt16WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(SInt16, kInt16POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt16WithISS")
}

// Defined at IArrayProperty.kl:43:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt32")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt32. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(UInt32, kUint32POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt32")
}

// Defined at IArrayProperty.kl:44:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt32WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt32WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt32WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsUInt32WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(UInt32, kUint32POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt32WithISS")
}

// Defined at IArrayProperty.kl:45:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt32")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt32. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(SInt32, kInt32POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt32")
}

// Defined at IArrayProperty.kl:46:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt32WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt32WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt32WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsSInt32WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(SInt32, kInt32POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt32WithISS")
}

// Defined at IArrayProperty.kl:47:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt64(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt64 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt64")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt64. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(UInt64, kUint64POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt64")
}

// Defined at IArrayProperty.kl:48:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsUInt64WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt64 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsUInt64WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsUInt64WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsUInt64WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(UInt64, kUint64POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsUInt64WithISS")
}

// Defined at IArrayProperty.kl:49:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt64(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt64 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt64")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt64. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(SInt64, kInt64POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt64")
}

// Defined at IArrayProperty.kl:50:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsSInt64WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt64 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsSInt64WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsSInt64WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsSInt64WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(SInt64, kInt64POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsSInt64WithISS")
}

// Defined at IArrayProperty.kl:51:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsFloat16(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsFloat16")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsFloat16. unable to convert: this_");
    return;
  }

  const Abc::PropertyHeader & header = abcThis_->getHeader();
  if(header.getDataType().getExtent() == 0)
    return;
  if(header.getDataType().getPod() != Abc::kFloat16POD)
    FABRIC_EXT_SETERROR_AND_RETURN("AlembicIArrayProperty_getAsFloat16: DataType.pod() not kFloat16POD.");
  AbcA::ArraySamplePtr sample;
  abcThis_->get(sample);
  if(!sample)
    return;
  if(sample->size() == 0)
    return;
  _result.resize(sample->size());
  Abc::float16_t * floats = (Abc::float16_t*)sample->getData();
  for(size_t i=0;i<sample->size();i++)
    _result[i] = floats[i];
    
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsFloat16")
}

// Defined at IArrayProperty.kl:52:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsFloat16WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsFloat16WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsFloat16WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsFloat16WithISS. unable to convert: iSS");
    return;
  }

  const Abc::PropertyHeader & header = abcThis_->getHeader();
  if(header.getDataType().getExtent() == 0)
    return;
  if(header.getDataType().getPod() != Abc::kFloat16POD)
    FABRIC_EXT_SETERROR_AND_RETURN("AlembicIArrayProperty_getAsFloat16: DataType.pod() not kFloat16POD.");
  AbcA::ArraySamplePtr sample;
  abcThis_->get(sample, *abcISS);
  if(!sample)
    return;
  if(sample->size() == 0)
    return;
  _result.resize(sample->size());
  Abc::float16_t * floats = (Abc::float16_t*)sample->getData();
  for(size_t i=0;i<sample->size();i++)
    _result[i] = floats[i];
    
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsFloat16WithISS")
}

// Defined at IArrayProperty.kl:53:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsFloat32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsFloat32")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsFloat32. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(Float32, kFloat32POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsFloat32")
}

// Defined at IArrayProperty.kl:54:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsFloat32WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsFloat32WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsFloat32WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsFloat32WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(Float32, kFloat32POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsFloat32WithISS")
}

// Defined at IArrayProperty.kl:55:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsFloat64(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float64 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsFloat64")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsFloat64. unable to convert: this_");
    return;
  }
  AlembicIArrayPropertyGetExport(Float64, kFloat64POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsFloat64")
}

// Defined at IArrayProperty.kl:56:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsFloat64WithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float64 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsFloat64WithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsFloat64WithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsFloat64WithISS. unable to convert: iSS");
    return;
  }
  AlembicIArrayPropertyGetWithISSExport(Float64, kFloat64POD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsFloat64WithISS")
}

// Defined at IArrayProperty.kl:57:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsString")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsString. unable to convert: this_");
    return;
  }

  const Abc::PropertyHeader & header = abcThis_->getHeader();
  if(header.getDataType().getExtent() == 0)
    return;

  AbcA::ArraySamplePtr sample;
  abcThis_->get(sample);
  if(!sample)
    return;
  if(sample->size() == 0)
    return;

  if(header.getDataType().getPod() == Abc::kStringPOD)
  {
    _result.resize(sample->size());
    std::string * strings = (std::string*)sample->getData();
    for(size_t i=0;i<sample->size();i++)
      _result[i] = strings[i];
  }
  else if(header.getDataType().getPod() == Abc::kWstringPOD)
  {
    _result.resize(sample->size());
    std::wstring * wstrings = (std::wstring*)sample->getData();
    for(size_t i=0;i<sample->size();i++)
    {
      std::string s;
      for(size_t j=0;j<wstrings[i].length();j++)
        s += wstrings[i][j];
      _result[i] = s.c_str();
    }
  }
  else
    FABRIC_EXT_SETERROR_AND_RETURN("AlembicIArrayProperty_getAsString: DataType.pod() not kStringPOD / kWstringPOD.");
    
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsString")
}

// Defined at IArrayProperty.kl:58:1
FABRIC_EXT_EXPORT void AlembicIArrayProperty_getAsStringWithISS(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIArrayProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISampleSelector >::INParam iSS
)
{
  ALEMBIC_TRY_STATEMENT("AlembicIArrayProperty_getAsStringWithISS")

  Abc::IArrayProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIArrayProperty, Abc::IArrayProperty>(this_, abcThis_)){
    setError("Error in AlembicIArrayProperty_getAsStringWithISS. unable to convert: this_");
    return;
  }
  Abc::ISampleSelector* abcISS = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISampleSelector, Abc::ISampleSelector>(iSS, abcISS)){
    setError("Error in AlembicIArrayProperty_getAsStringWithISS. unable to convert: iSS");
    return;
  }

  const Abc::PropertyHeader & header = abcThis_->getHeader();
  if(header.getDataType().getExtent() == 0)
    return;

  AbcA::ArraySamplePtr sample;
  abcThis_->get(sample, *abcISS);
  if(!sample)
    return;
  if(sample->size() == 0)
    return;

  if(header.getDataType().getPod() == Abc::kStringPOD)
  {
    _result.resize(sample->size());
    std::string * strings = (std::string*)sample->getData();
    for(size_t i=0;i<sample->size();i++)
      _result[i] = strings[i];
  }
  else if(header.getDataType().getPod() == Abc::kWstringPOD)
  {
    _result.resize(sample->size());
    std::wstring * wstrings = (std::wstring*)sample->getData();
    for(size_t i=0;i<sample->size();i++)
    {
      std::string s;
      for(size_t j=0;j<wstrings[i].length();j++)
        s += wstrings[i][j];
      _result[i] = s.c_str();
    } 
  }
  else
    FABRIC_EXT_SETERROR_AND_RETURN("AlembicIArrayProperty_getAsString: DataType.pod() not kStringPOD / kWstringPOD.");
    
  ALEMBIC_CATCH_STATEMENT("AlembicIArrayProperty_getAsStringWithISS")
}
