////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicONuPatch_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at ONuPatch.kl:9:1
FABRIC_EXT_EXPORT void AlembicONuPatch_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatch >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatch_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicONuPatch_construct")
}

// Defined at ONuPatch.kl:10:1
FABRIC_EXT_EXPORT void AlembicONuPatch_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatch >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatch_free")

  AbcG::ONuPatch* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatch, AbcG::ONuPatch>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::ONuPatch)
  
  ALEMBIC_CATCH_STATEMENT("AlembicONuPatch_free")
}

// Defined at ONuPatch.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicONuPatch_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatch >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatch_valid")

  AbcG::ONuPatch* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatch, AbcG::ONuPatch>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicONuPatch_valid", false)
}

// Defined at ONuPatch.kl:14:1
FABRIC_EXT_EXPORT void AlembicONuPatch_construct3Args(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatch >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOObject >::INParam parent,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam timeSampling
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatch_construct3Args")

  Abc::OObject* abcParent = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOObject, Abc::OObject>(parent, abcParent)){
    setError("Error in AlembicONuPatch_construct3Args. unable to convert: parent");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicONuPatch_construct3Args. unable to convert: name");
    return;
  }
  unsigned int abcTimeSampling = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(timeSampling, abcTimeSampling)){
    setError("Error in AlembicONuPatch_construct3Args. unable to convert: timeSampling");
    return;
  }

  AbcG::ONuPatch * abcThis_ = new AbcG::ONuPatch(*abcParent, abcName, abcTimeSampling);
  this_->handle = new PtrHandle<AbcG::ONuPatch>(abcThis_, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicONuPatch_construct3Args")
}

// Defined at ONuPatch.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicONuPatch_matches(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatch >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::INParam metaData
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatch_matches")

  AbcG::ONuPatch* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatch, AbcG::ONuPatch>(this_, abcThis_)){
    setError("Error in AlembicONuPatch_matches. unable to convert: this_");
    return false;
  }
  Abc::MetaData * abcMetaData = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicMetaData, Abc::MetaData>(metaData, abcMetaData)){
    setError("Error in AlembicONuPatch_matches. unable to convert: metaData");
    return false;
  }
  return AbcG::ONuPatch::matches(*abcMetaData);
  
  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicONuPatch_matches", false)
}

// Defined at ONuPatch.kl:19:1
FABRIC_EXT_EXPORT void AlembicONuPatch_getSchema(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatchSchema >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicONuPatch >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicONuPatch_getSchema")

  AbcG::ONuPatch* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicONuPatch, AbcG::ONuPatch>(this_, abcThis_)){
    setError("Error in AlembicONuPatch_getSchema. unable to convert: this_");
    return;
  }
  AbcG::ONuPatchSchema* abc_result = new AbcG::ONuPatchSchema(abcThis_->getSchema());
  conv_to_AbcBasePtr<KL::AlembicONuPatchSchema, AbcG::ONuPatchSchema>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicONuPatch_getSchema")
}
