////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicOLightSchema_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at OLightSchema.kl:9:1
FABRIC_EXT_EXPORT void AlembicOLightSchema_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicOLightSchema_construct")
}

// Defined at OLightSchema.kl:10:1
FABRIC_EXT_EXPORT void AlembicOLightSchema_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_free")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::OLightSchema)
  
  ALEMBIC_CATCH_STATEMENT("AlembicOLightSchema_free")
}

// Defined at OLightSchema.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOLightSchema_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_valid")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOLightSchema_valid", false)
}

// Defined at OLightSchema.kl:14:1
FABRIC_EXT_EXPORT void AlembicOLightSchema_getTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicTimeSampling >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_getTimeSampling")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    setError("Error in AlembicOLightSchema_getTimeSampling. unable to convert: this_");
    return;
  }
  Abc::TimeSamplingPtr abc_result = abcThis_->getTimeSampling();
  conv_to_AbcBase<KL::AlembicTimeSampling, Abc::TimeSamplingPtr>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicOLightSchema_getTimeSampling")
}

// Defined at OLightSchema.kl:15:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicOLightSchema_getNumSamples(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_getNumSamples")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    setError("Error in AlembicOLightSchema_getNumSamples. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getNumSamples();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOLightSchema_getNumSamples", 0)
}

// Defined at OLightSchema.kl:16:1
FABRIC_EXT_EXPORT void AlembicOLightSchema_setTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_setTimeSampling")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    setError("Error in AlembicOLightSchema_setTimeSampling. unable to convert: this_");
    return;
  }
  unsigned int abcIndex = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(index, abcIndex)){
    setError("Error in AlembicOLightSchema_setTimeSampling. unable to convert: index");
    return;
  }
  abcThis_->setTimeSampling(abcIndex);

  ALEMBIC_CATCH_STATEMENT("AlembicOLightSchema_setTimeSampling")
}

// Defined at OLightSchema.kl:17:1
FABRIC_EXT_EXPORT void AlembicOLightSchema_getArbGeomParams(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_getArbGeomParams")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    setError("Error in AlembicOLightSchema_getArbGeomParams. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getArbGeomParams());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOLightSchema_getArbGeomParams")
}

// Defined at OLightSchema.kl:18:1
FABRIC_EXT_EXPORT void AlembicOLightSchema_getUserProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_getUserProperties")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    setError("Error in AlembicOLightSchema_getUserProperties. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getUserProperties());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOLightSchema_getUserProperties")
}

// Defined at OLightSchema.kl:19:1
FABRIC_EXT_EXPORT void AlembicOLightSchema_getChildBoundsProperty(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOScalarProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOLightSchema >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOLightSchema_getChildBoundsProperty")

  AbcG::OLightSchema* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOLightSchema, AbcG::OLightSchema>(this_, abcThis_)){
    setError("Error in AlembicOLightSchema_getChildBoundsProperty. unable to convert: this_");
    return;
  }
  Abc::OScalarProperty* abc_result = new Abc::OScalarProperty(abcThis_->getChildBoundsProperty());
  conv_to_AbcBasePtr<KL::AlembicOScalarProperty, Abc::OScalarProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOLightSchema_getChildBoundsProperty")
}
