////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicOCompoundProperty_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at OCompoundProperty.kl:9:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_construct")
}

// Defined at OCompoundProperty.kl:10:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_free")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::OCompoundProperty)
  
  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_free")
}

// Defined at OCompoundProperty.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOCompoundProperty_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_valid")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCompoundProperty_valid", false)
}

// Defined at OCompoundProperty.kl:14:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_construct2Args(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam parent,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_construct2Args")

  Abc::OCompoundProperty* abcParent = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(parent, abcParent)){
    setError("Error in AlembicOCompoundProperty_construct2Args. unable to convert: parent");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicOCompoundProperty_construct2Args. unable to convert: name");
    return;
  }

  Abc::OCompoundProperty * abcThis_ = new Abc::OCompoundProperty(*abcParent, abcName);
  this_->handle = new PtrHandle<Abc::OCompoundProperty>(abcThis_, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_construct2Args")
}

// Defined at OCompoundProperty.kl:16:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getHeader(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicPropertyHeader >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getHeader")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getHeader. unable to convert: this_");
    return;
  }
  AlembicPropertyGetHeader()
  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getHeader")
}

// Defined at OCompoundProperty.kl:17:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getName")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getName. unable to convert: this_");
    return;
  }
  std::string abc_result = abcThis_->getName();
  conv_to_String(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getName")
}

// Defined at OCompoundProperty.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicOCompoundProperty_getPropertyType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getPropertyType")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getPropertyType. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getPropertyType();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCompoundProperty_getPropertyType", 0)
}

// Defined at OCompoundProperty.kl:19:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOCompoundProperty_isScalar(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_isScalar")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_isScalar. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isScalar();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCompoundProperty_isScalar", false)
}

// Defined at OCompoundProperty.kl:20:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOCompoundProperty_isArray(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_isArray")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_isArray. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isArray();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCompoundProperty_isArray", false)
}

// Defined at OCompoundProperty.kl:21:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOCompoundProperty_isCompound(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_isCompound")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_isCompound. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isCompound();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCompoundProperty_isCompound", false)
}

// Defined at OCompoundProperty.kl:22:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOCompoundProperty_isSimple(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_isSimple")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_isSimple. unable to convert: this_");
    return false;
  }
  bool abc_result = abcThis_->isSimple();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCompoundProperty_isSimple", false)
}

// Defined at OCompoundProperty.kl:23:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getMetaData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getMetaData")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getMetaData. unable to convert: this_");
    return;
  }
  AlembicGetMetaData()
  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getMetaData")
}

// Defined at OCompoundProperty.kl:24:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getDataType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicDataType >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getDataType")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getDataType. unable to convert: this_");
    return;
  }
  Abc::DataType abc_result = abcThis_->getDataType();
  conv_to_AbcBase<KL::AlembicDataType, Abc::DataType>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getDataType")
}

// Defined at OCompoundProperty.kl:25:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getTimeSampling(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicTimeSampling >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getTimeSampling")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getTimeSampling. unable to convert: this_");
    return;
  }
  Abc::TimeSamplingPtr abc_result = abcThis_->getTimeSampling();
  conv_to_AbcBase<KL::AlembicTimeSampling, Abc::TimeSamplingPtr>(abc_result, _result);

  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getTimeSampling")
}

// Defined at OCompoundProperty.kl:26:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getObject(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOObject >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getObject")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getObject. unable to convert: this_");
    return;
  }
  Abc::OObject* abc_result = new Abc::OObject(abcThis_->getObject());
  conv_to_AbcBasePtr<KL::AlembicOObject, Abc::OObject>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getObject")
}

// Defined at OCompoundProperty.kl:28:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 AlembicOCompoundProperty_getNumProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getNumProperties")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getNumProperties. unable to convert: this_");
    return 0;
  }
  unsigned int abc_result = abcThis_->getNumProperties();
  KL::UInt32 _result;
  conv_to_baseType<KL::UInt32, unsigned int>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOCompoundProperty_getNumProperties", 0)
}

// Defined at OCompoundProperty.kl:29:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getPropertyHeader(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicPropertyHeader >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam propertyIndex
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getPropertyHeader")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getPropertyHeader. unable to convert: this_");
    return;
  }
  unsigned int abcPropertyIndex = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(propertyIndex, abcPropertyIndex)){
    setError("Error in AlembicOCompoundProperty_getPropertyHeader. unable to convert: propertyIndex");
    return;
  }

  Abc::PropertyHeader abc_result = abcThis_->getPropertyHeader(abcPropertyIndex);
  conv_to_AbcBasePtr<KL::AlembicPropertyHeader, Abc::PropertyHeader>(&abc_result, _result);
    
  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getPropertyHeader")
}

// Defined at OCompoundProperty.kl:30:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getPropertyHeaderByName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicPropertyHeader >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam propertyName
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getPropertyHeaderByName")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getPropertyHeaderByName. unable to convert: this_");
    return;
  }
  std::string abcPropertyName = "";
  if(!conv_from_String(propertyName, abcPropertyName)){
    setError("Error in AlembicOCompoundProperty_getPropertyHeaderByName. unable to convert: propertyName");
    return;
  }

  const Abc::PropertyHeader * abc_result = abcThis_->getPropertyHeader(abcPropertyName);
  conv_to_AbcBasePtr<KL::AlembicPropertyHeader, Abc::PropertyHeader>((Abc::PropertyHeader *)abc_result, _result);
    
  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getPropertyHeaderByName")
}

// Defined at OCompoundProperty.kl:31:1
FABRIC_EXT_EXPORT void AlembicOCompoundProperty_getParent(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOCompoundProperty >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOCompoundProperty_getParent")

  Abc::OCompoundProperty* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(this_, abcThis_)){
    setError("Error in AlembicOCompoundProperty_getParent. unable to convert: this_");
    return;
  }
  Abc::OCompoundProperty* abc_result = new Abc::OCompoundProperty(abcThis_->getParent());
  conv_to_AbcBasePtr<KL::AlembicOCompoundProperty, Abc::OCompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOCompoundProperty_getParent")
}
