////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicOPolyMesh_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at OPolyMesh.kl:9:1
FABRIC_EXT_EXPORT void AlembicOPolyMesh_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPolyMesh >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPolyMesh_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicOPolyMesh_construct")
}

// Defined at OPolyMesh.kl:10:1
FABRIC_EXT_EXPORT void AlembicOPolyMesh_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPolyMesh >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPolyMesh_free")

  AbcG::OPolyMesh* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPolyMesh, AbcG::OPolyMesh>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::OPolyMesh)
  
  ALEMBIC_CATCH_STATEMENT("AlembicOPolyMesh_free")
}

// Defined at OPolyMesh.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOPolyMesh_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPolyMesh >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPolyMesh_valid")

  AbcG::OPolyMesh* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPolyMesh, AbcG::OPolyMesh>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOPolyMesh_valid", false)
}

// Defined at OPolyMesh.kl:14:1
FABRIC_EXT_EXPORT void AlembicOPolyMesh_construct3Args(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPolyMesh >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOObject >::INParam parent,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam timeSampling
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPolyMesh_construct3Args")

  Abc::OObject* abcParent = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOObject, Abc::OObject>(parent, abcParent)){
    setError("Error in AlembicOPolyMesh_construct3Args. unable to convert: parent");
    return;
  }
  std::string abcName = "";
  if(!conv_from_String(name, abcName)){
    setError("Error in AlembicOPolyMesh_construct3Args. unable to convert: name");
    return;
  }
  unsigned int abcTimeSampling = 0;
  if(!conv_from_baseType<KL::UInt32, unsigned int>(timeSampling, abcTimeSampling)){
    setError("Error in AlembicOPolyMesh_construct3Args. unable to convert: timeSampling");
    return;
  }

  AbcG::OPolyMesh * abcThis = new AbcG::OPolyMesh(*abcParent, std::string(name.data()), timeSampling);
  this_->handle = new PtrHandle<AbcG::OPolyMesh>(abcThis, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicOPolyMesh_construct3Args")
}

// Defined at OPolyMesh.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicOPolyMesh_matches(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPolyMesh >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::INParam metaData
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPolyMesh_matches")

  AbcG::OPolyMesh* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPolyMesh, AbcG::OPolyMesh>(this_, abcThis_)){
    setError("Error in AlembicOPolyMesh_matches. unable to convert: this_");
    return false;
  }
  Abc::MetaData * abcMetaData = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicMetaData, Abc::MetaData>(metaData, abcMetaData)){
    setError("Error in AlembicOPolyMesh_matches. unable to convert: metaData");
    return false;
  }
  return AbcG::OPolyMesh::matches(*abcMetaData);
  
  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicOPolyMesh_matches", false)
}

// Defined at OPolyMesh.kl:19:1
FABRIC_EXT_EXPORT void AlembicOPolyMesh_getSchema(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPolyMeshSchema >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicOPolyMesh >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicOPolyMesh_getSchema")

  AbcG::OPolyMesh* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicOPolyMesh, AbcG::OPolyMesh>(this_, abcThis_)){
    setError("Error in AlembicOPolyMesh_getSchema. unable to convert: this_");
    return;
  }
  AbcG::OPolyMeshSchema* abc_result = new AbcG::OPolyMeshSchema(abcThis_->getSchema());
  conv_to_AbcBasePtr<KL::AlembicOPolyMeshSchema, AbcG::OPolyMeshSchema>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicOPolyMesh_getSchema")
}
