////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.2
////////////////////////////////////////////////////////////////

#include "AlembicISubD_functions.h"


#include "extension.h"
  

using namespace Fabric::EDK;


// Defined at ISubD.kl:9:1
FABRIC_EXT_EXPORT void AlembicISubD_construct(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubD >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicISubD_construct")

  this_->handle = NULL;
  
  ALEMBIC_CATCH_STATEMENT("AlembicISubD_construct")
}

// Defined at ISubD.kl:10:1
FABRIC_EXT_EXPORT void AlembicISubD_free(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubD >::IOParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicISubD_free")

  AbcG::ISubD* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISubD, AbcG::ISubD>(this_, abcThis_)){
    return;
  }
  free_AbcBasePtr(AbcG::ISubD)
  
  ALEMBIC_CATCH_STATEMENT("AlembicISubD_free")
}

// Defined at ISubD.kl:11:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicISubD_valid(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubD >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicISubD_valid")

  AbcG::ISubD* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISubD, AbcG::ISubD>(this_, abcThis_)){
    return false;
  }
  bool abc_result = abcThis_->valid();
  KL::Boolean _result;
  conv_to_baseType<KL::Boolean, bool>(abc_result, _result);
  return _result;

  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicISubD_valid", false)
}

// Defined at ISubD.kl:14:1
FABRIC_EXT_EXPORT void AlembicISubD_constructFromIObject(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubD >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicIObject >::INParam obj
)
{
  ALEMBIC_TRY_STATEMENT("AlembicISubD_constructFromIObject")

  Abc::IObject* abcObj = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicIObject, Abc::IObject>(obj, abcObj)){
    setError("Error in AlembicISubD_constructFromIObject. unable to convert: obj");
    return;
  }

  AbcG::ISubD * abcThis_ = new AbcG::ISubD(*abcObj, Abc::kWrapExisting);
  this_->handle = new PtrHandle<AbcG::ISubD>(abcThis_, true);
    
  ALEMBIC_CATCH_STATEMENT("AlembicISubD_constructFromIObject")
}

// Defined at ISubD.kl:18:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean AlembicISubD_matches(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubD >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicMetaData >::INParam metaData
)
{
  ALEMBIC_TRY_STATEMENT("AlembicISubD_matches")

  Abc::MetaData * abcMetaData = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicMetaData, Abc::MetaData>(metaData, abcMetaData)){
    setError("Error in AlembicISubD_matches. unable to convert: metaData");
    return false;
  }
  return AbcG::ISubD::matches(*abcMetaData);
  
  ALEMBIC_CATCH_STATEMENT_RETURN("AlembicISubD_matches", false)
}

// Defined at ISubD.kl:19:1
FABRIC_EXT_EXPORT void AlembicISubD_getProperties(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicICompoundProperty >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubD >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicISubD_getProperties")

  AbcG::ISubD* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISubD, AbcG::ISubD>(this_, abcThis_)){
    setError("Error in AlembicISubD_getProperties. unable to convert: this_");
    return;
  }
  Abc::ICompoundProperty* abc_result = new Abc::ICompoundProperty(abcThis_->getProperties());
  conv_to_AbcBasePtr<KL::AlembicICompoundProperty, Abc::ICompoundProperty>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicISubD_getProperties")
}

// Defined at ISubD.kl:20:1
FABRIC_EXT_EXPORT void AlembicISubD_getSchema(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubDSchema >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AlembicISubD >::INParam this_
)
{
  ALEMBIC_TRY_STATEMENT("AlembicISubD_getSchema")

  AbcG::ISubD* abcThis_ = NULL;
  if(!conv_from_AbcBasePtr<KL::AlembicISubD, AbcG::ISubD>(this_, abcThis_)){
    setError("Error in AlembicISubD_getSchema. unable to convert: this_");
    return;
  }
  AbcG::ISubDSchema* abc_result = new AbcG::ISubDSchema(abcThis_->getSchema());
  conv_to_AbcBasePtr<KL::AlembicISubDSchema, AbcG::ISubDSchema>(abc_result, _result, true);

  ALEMBIC_CATCH_STATEMENT("AlembicISubD_getSchema")
}
