#!/bin/bash

export FABRIC_VERSION=1.13.0
export BOOST_INCLUDE_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/boost/1.55.0
export BOOST_LIBRARY_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/boost/1.55.0/lib
export ILMBASE_INCLUDE_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/include/ilmbase
export ILMBASE_LIBRARY_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/lib/ilmbase
export ZLIB_INCLUDE_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/include/zlib
export ZLIB_LIBRARY_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/lib/zlib
export HDF5_INCLUDE_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/hdf5/1.8.7/include
export HDF5_LIBRARY_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/hdf5/1.8.7/lib
export ALEMBIC_INCLUDE_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/alembic/1.5.3_2013121700/include
export ALEMBIC_LIBRARY_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/alembic/1.5.3_2013121700/lib
